name = "nautica"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
account_id = "e8de976c4f335309e91da49ce403215c"
workers_dev = true
logpush = true

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
